# Generated by Django 2.2.6 on 2019-11-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
