# Generated by Django 2.2.6 on 2019-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191101_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='start_use_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата загрузки в библиотеку'),
        ),
    ]
